### ISSUE TITLE
Tracking issue for release `0.2.0`

### ISSUE THREAD

**Issue by xushiyan** [apache/hudi-rs#193]
### Issues

- [x] All remaining issues in the [milestone](https://github.com/apache/hudi-rs/milestone/2) should be closed.

### GitHub

- [x] Bump version
- [x] Push release tag

### ASF

- [x] Create an ASF release
- [x] Upload artifacts to the SVN dist repo
- [x] Start VOTE in dev email list

> [!IMPORTANT]
> Proceed from here only after VOTE passes.

### Official release

- [x] Push the release git tag
- [x] Publish artifacts to SVN RELEASE branch
- [x] Send `ANNOUNCE` email to dev and user email lists

**Comment by xushiyan** [comment]
# Changelog

All notable changes to this project will be documented in this file.

## [unreleased]

### 🚀 Features

- Support loading hudi global configs (#118) by @zzhpro
- Add base file records' in-memory size to `FileStats` (#140) by @xushiyan
- Support partition prune api (#119) by @KnightChess
- Add partition filter arg in Python APIs (#153) by @xushiyan
- Add `HudiFileGroupReader` with consolidated APIs to read records (#164) by @xushiyan
- Add `TableBuilder` API for creating `Table` instances (#163) by @kazdy
- Implement datafusion `TableProviderFactory` (#162) by @kazdy

### 🐛 Bug Fixes

- Register object store with datafusion (#107) by @abyssnlp
- Handle validating table when `DropsPartitionFields` not present (#142) by @xushiyan
- Make partition loading more efficient (#152) by @xushiyan
- Simplify partition filter format by taking tuple of strings (#170)
- Improve api to get file slices splits (#185)
- Handle schema retrieval for datafusion api (#187)

### 🚜 Refactor

- Extract common test code for creating table (#117) by @gohalo
- Improve APIs for handling options (#161) by @xushiyan
- Improve `TableBuilder` API for taking single option (#171) by @xushiyan
- Minor improvement to fix coverage report status (#173) by @xushiyan

### 📚 Documentation

- Update readme logo and example (#65) by @xushiyan
- Update in-code comments (#132) by @KnightChess
- Add hudi core API docs with examples (#113) by @KnightChess
- Add in-code docs to hudi-core APIs (#166) by @xushiyan
- Add python binding docstrings (#169) by @kazdy
- Add step-by-step release guide (#66) by @xushiyan
- Update README examples (#194)
- Update release and dev guides (#195)

### 🎨 Styling

- Enforce Python code style (#101) by @muyihao

### 🛠️ Build

- Use exact versions for arrow and datafusion (#105) by @xushiyan
- Bump up datafusion to version 41, arrow to 52.2 (#120) by @yjshen
- *(deps)* Update zip-extract requirement from 0.1.3 to 0.2.1 (#130) by @dependabot[bot]
- *(deps)* Upgrade datafusion, pyarrow, pyo3, python versions  (#149) by @kazdy
- *(deps)* Upgrade arrow dependencies (#168) by @kazdy
- *(deps)* Upgrade datafusion and object store (#182)
- *(deps)* Upgrade datafusion to 42.2.0 (#192)

### ⚙️ Miscellaneous Tasks

- Improve release scripts (#68) by @xushiyan
- Add `CHANGELOG.md` with git-cliff config (#69) by @xushiyan
- Configure labeler for PRs from forked repos (#83) by @xushiyan
- Fix labeler config (#85) by @xushiyan
- Fix labeler config for dev-x (#87) by @xushiyan
- Merge python code coverage report with rust (#67) by @xushiyan
- Add pull request template (#89) by @xushiyan
- Enable dependabot (#94) by @xushiyan
- Add path ignore files for ci workflow (#93) by @abyssnlp
- Improve workflows for code checking and PR (#110) by @xushiyan
- Disable labeler due to permission and policy (#115) by @xushiyan
- *(ci)* Fix PR title linting to support change scope (#138) by @kazdy
- Add feature request template for GH issues (#167) by @kazdy

## New Contributors

* @KnightChess made their first contribution in #119

* @gohalo made their first contribution in #117

* @zzhpro made their first contribution in #118

* @yjshen made their first contribution in #120

* @abyssnlp made their first contribution in #107

* @muyihao made their first contribution in #101
