### ISSUE TITLE
Tracking issue for release `0.1.0`

### ISSUE THREAD

**Issue by xushiyan** [apache/hudi-rs#62]
### Issues

- [x] This issue is added to [the target milestone](https://github.com/apache/hudi-rs/milestone/1)

> [!CAUTION]
> Blockers to highlight

- [x] https://github.com/apache/hudi-rs/issues/41
- [x] https://github.com/apache/hudi-rs/issues/42

### GitHub

- [x] Bump version
- [x] Create release tag with suffix `-rc.X`
- [x] Publish artifacts to pypi.org
- [x] Publish artifacts to crates.io

### ASF

- [x] Create an ASF release
- [x] Upload artifacts to the SVN dist repo
- [x] Start VOTE in dev email list

> [!CAUTION]
> Proceed from here only after VOTE passes.

### Official release

- [x] Push the release git tag
- [x] Publish artifacts to SVN RELEASE branch
- [x] Update release data in https://reporter.apache.org/wizard/statistics?hudi
- [x] Generate release notes and update `CHANGELOG.md`
- [x] Send `ANNOUNCE` email to dev and user email lists

**Comment by xushiyan** [comment]
# Changelog

## [release-0.1.0-rc.2] - 2024-07-12

### Build

- Bump version to 0.1.0-rc.2

## [release-0.1.0-rc.1] - 2024-07-12

### 🚀 Features

- Initial rust implementation to integrate with datafusion (#1)
- Add python binding (#21)
- Implement `HudiTable` as python API (#23)
- Use `object_store` for common storage APIs (#25)
- Implement Rust and Python APIs to read file slices (#28)
- Add APIs for time-travel read (#33)
- Implement datafusion API using ParquetExec (#35)
- Add `HudiConfigs` for parsing and managing named configs (#37)
- Add config validation when creating table (#49)
- Add internal config to skip validation (#51)
- Support time travel with read option (#52)
- Support taking env vars for cloud storages (#55)

### 🐛 Bug Fixes

- Handle replacecommit for loading file slices (#53)

### 🚜 Refactor

- Use `anyhow` for generic errors (#26)
- Use `object_store` API for Timeline (#27)
- Make APIs async (#31)
- Improve thread safety and error handling (#32)
- Improve error handling in storage module (#34)
- Adjust table APIs to skip passing options (#56)

### 📚 Documentation

- Update readme, contributing guide, and issue template (#57)
- Update CONTRIBUTING with minor changes (#58)

### 🎨 Styling

- Enforce rust code style (#14)

### 🧪 Testing

- Add tests crate and adopt testing tables (#30)
- Add test cases for different table setup (#36)

### ⚙️ Miscellaneous Tasks

- Setup ci for license file and headers (#2)
- Fix failing check and test case (#10)
- Fix asf notification (#11)
- Add commit linting (#12)
- Use cargo tarpaulin to generate code coverage (#15)
- Remove codecov to keep ci green (#17)
- Fix codecov setup (#20)
- Configure codecov (#50)
- Add scripts to streamline source release (#64)

### Build

- Clean up and trim down dependencies (#54)
- Add info for rust and python artifacts (#60)
- Add release workflow (#63)
- Bump version to 0.1.0-rc.1
